name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    #strategy:
     # matrix:
      #  node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Build and Run Test
      run: |
        ls
        cd TestScripts
        ls
      # "${GITHUB_WORKSPACE}/TestScripts/javac HelloWorld.java"
      # "${GITHUB_WORKSPACE}/TestScripts/Java HelloWorld.java"
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v3
      if: always() # always run even if the previous step fails
      with:
        report_paths: "**/build/test-results/test/TEST-*.xml"
   # - name: Use Node.js ${{ matrix.node-version }}
    #  uses: actions/setup-node@v1
     # with:
      #  node-version: ${{ matrix.node-version }}
   # - run: npm install -g npm@6
   # - run: npm test
